### ISSUE TITLE
No job listings for some schools

### ISSUE THREAD

**Issue by tatyree** [DFE-Digital/teacher-vacancy-service#1675]
## Background

Comms have relayed a message from an external user stating that, since mid May, schools that they were expecting to have listings were returning no listings.  Specific examples given were for Downlands Community School, Finham Park School, St Albans Girls' School.

**Comment by tatyree** [comment]
Downlands Community School: 

<img width="1005" alt="Screenshot 2020-06-23 at 15 04 31" src="https://user-images.githubusercontent.com/20921/85413662-00ead080-b563-11ea-913c-67c2289d0bf4.png">

**Comment by tatyree** [comment]
Finham Park School:

<img width="1024" alt="Screenshot 2020-06-23 at 15 06 21" src="https://user-images.githubusercontent.com/20921/85413786-28419d80-b563-11ea-8472-437bd3b31698.png">

**Comment by tatyree** [comment]
St Albans Girls' School:

<img width="1060" alt="Screenshot 2020-06-23 at 15 07 44" src="https://user-images.githubusercontent.com/20921/85413904-54f5b500-b563-11ea-9d20-eec5bcf216c2.png">

**Comment by tatyree** [comment]
Downlands Community School in location: 

<img width="1039" alt="Screenshot 2020-06-23 at 15 08 58" src="https://user-images.githubusercontent.com/20921/85414039-840c2680-b563-11ea-8d8e-d9dffceaea7f.png">

**Comment by tatyree** [comment]
Finham Park School

<img width="1128" alt="Screenshot 2020-06-23 at 15 10 05" src="https://user-images.githubusercontent.com/20921/85414171-ac942080-b563-11ea-90ff-4a61a4de2421.png">

**Comment by tatyree** [comment]
St Albans Girls' School in location: 

<img width="1066" alt="Screenshot 2020-06-23 at 15 11 41" src="https://user-images.githubusercontent.com/20921/85414345-e36a3680-b563-11ea-81d0-1c8d87b5e968.png">

**Comment by tatyree** [comment]
All were searched against the production site.  The only one that yielded no 'results' was using 'Downlands Community School' in location.  I'll need to speak with the person that raised the bug directly to progress this further.

**Comment by cpjmcquillan** [comment]
Worth noting that the quality of the location search here is reliant on an external service successfully geocoding the school name as a location
