### ISSUE TITLE
Create LocationPolygon model

### ISSUE THREAD

**Issue by cpjmcquillan** [DFE-Digital/teacher-vacancy-service#1681]
## Create a new model for location polygons

Proposed fields include:
- Location name _string_ **required**
- Location type _string (region,_ city, county, local authority etc)
- Boundary _float array_ (polygon boundary data in the form Algolia uses [lat0, lng0, ..., latN, lngN])
- Is Active? _boolean_ (indicates whether the polygon should be used for location searches, could be used in future to turn location landing pages off/on for instance)

For reference:
- [Spike model](https://github.com/DFE-Digital/teacher-vacancy-service/blob/bcdb287d40cd86ca091b3b9f1cd691486e696fe7/app/models/location_polygon.rb)
- [Spike schema](https://github.com/DFE-Digital/teacher-vacancy-service/blob/bcdb287d40cd86ca091b3b9f1cd691486e696fe7/db/migrate/20200623081123_create_location_polygons.rb)

## Acceptance criteria
- [x] Model exists
- [x] Schema updated
- [x] Code review

**Comment by bencmitchell** [comment]
https://dfedigital.atlassian.net/browse/TEVA-942
