### ISSUE TITLE
Create a task that consumes boundaries data

### ISSUE THREAD

**Issue by cpjmcquillan** [DFE-Digital/teacher-vacancy-service#1682]
## Create a task for importing boundary data

A task needs to be created that calls out to the relevant [ONS APIs](https://geoportal.statistics.gov.uk/) in order to populate LocationPolygon records. The task needn't be run on a scheduled basis, since data is unlikely to change frequently.

The task should be configurable so that:
- Any combination of location types can be run (regions, cities, counties, local authorities, etc)
- Flag can be set to overwrite data for existing LocationPolygon records or not
- Flag can be set to specify boundary resolution (and therefore which API endpoint)
- LocationPolygon records should not be created for locations that are "out of scope"
- Location name field should be set as a single case string

For reference:
- [Spike task](https://github.com/DFE-Digital/teacher-vacancy-service/blob/bcdb287d40cd86ca091b3b9f1cd691486e696fe7/lib/tasks/fetch_location_polygon_boundary_data.rake)

## Acceptance criteria
- [x] Configurable task exists that can be run on demand to import boundary data
- [x] Code review
- [x] Product sign off on default resolution
- [x] Product sign off on out of scope locations

**Comment by bencmitchell** [comment]
https://dfedigital.atlassian.net/browse/TEVA-945
