### ISSUE TITLE
Implement server side location polygon search

### ISSUE THREAD

**Issue by cpjmcquillan** [DFE-Digital/teacher-vacancy-service#1684]
## Implement polygon search in Algolia for locations where appropriate

For the relevant locations (as defined in [TEVA-943](https://dfedigital.atlassian.net/browse/TEVA-943) and #1682)`insidePolygon` search is carried out in Algolia.

For reference:
```ruby
Vacancy.search('query', { insidePolygon: 'string of comma separated floats' })
```

## Acceptance criteria
- [ ] Server side search (including job alerts) carries out location polygon searches where appropriate 
- [ ] Code review

**Comment by bencmitchell** [comment]
https://dfedigital.atlassian.net/browse/TEVA-950
