### ISSUE TITLE
Search client can consume location API

### ISSUE THREAD

**Issue by cpjmcquillan** [DFE-Digital/teacher-vacancy-service#1685]
## Search client can consume location API

Implement/refactor method(s) to remove client-side logic and use data returned by the location API to carry out the appropriate search for a given location.

For reference:
- [Spike method](https://github.com/DFE-Digital/teacher-vacancy-service/blob/bcdb287d40cd86ca091b3b9f1cd691486e696fe7/app/frontend/src/lib/api.js)

## Acceptance criteria
- [ ] Client side method exists to consume location API and retrieve relevant data
- [ ] Code review

**Comment by bencmitchell** [comment]
https://dfedigital.atlassian.net/browse/TEVA-948
