### ISSUE TITLE
Change vacancy so it can belong to a school or a school_group (aka trust)

### ISSUE THREAD

**Issue by tatyree** [DFE-Digital/teacher-vacancy-service#1731]
## Background

An initial requirement of Multi Academy Trust (MAT) access to TVS is that trusts can list vacancies for jobs at the trust, proper, or any number of schools in the trust.  Our current vacancy data model does not fully enable this behaviour, so we need to change it such that a vacancy can belong to a trust or a school.  

Eventually, a vacancy will need to belong to a trust and/or any number of schools in that trust, but this is out of scope for this issue.

## Done when

 - [x] A vacancy can belong to a school **or** a trust (a school association is currently required)
 - [x] The owning organisation of the school is returned by a single method call (`school_or_trust`)
 - [ ] All occurrences of `Vacancy#school` have been changed to use this new method call
 - [x] The code has been PR'd and approved
 - [ ] The code has been merged to master 
 - [ ] The code has been released to production

## Notes

The current `school` association is declared here: 
https://github.com/DFE-Digital/teacher-vacancy-service/blob/master/app/models/vacancy.rb#L214

This code will only change back end implementation details.  Once the new method call has been implemented across the codebase it is safe to release to production as is regardless of the implementation status of the other MAT tickets.

**Comment by cpjmcquillan** [comment]
Not all instances of `vacancy.school` have been updated in #1732. This isn't necessary at this stage, but should be updated as the feature develops and the SchoolGroup object is refined further and the appropriate methods and properties are added.
