### ISSUE TITLE
Create NQT job alert templates in Notify 

### ISSUE THREAD

**Issue by tatyree** [DFE-Digital/teacher-vacancy-service#1739]
[TEVA-1009](https://dfedigital.atlassian.net/browse/TEVA-1009)

## Background 

After discussions, we believe we need specific template(s) to help NQT navigate job alerts and find jobs.  We may also need alterations to the copy of some of the existing templates, but this should be done as part of a different issue. 

Our current [mailer gem](https://github.com/dxw/mail-notify) encourages use of the Rails views in place of Notify templates, but [will support ordinary Notify templating](https://github.com/dxw/mail-notify#with-notify-templating).  

We want to consistently use Notify templates to maintain email body copy as they reduce the burden of maintaining that copy, make the templates simpler and quicker to change, and make it possible for Content to maintain/update the templates themselves. 

## Done when

- [ ] A new folder exists on Notify labelled 'NQT recruitment'
- [ ] All required templates are created in that folder with the correct copy and necessary placeholders.
    - [ ] (probably - @valentine-carter to confirm) An NQT specific alert template
    - [ ] A 'confirm your email and subscription' template that lets jobseekers click on a **timed** link to prove they are the person who signed up for the alert (details for the link in #1740). 
- [ ] Notify templating is used **correctly** - i.e. the body of the message has the actual copy in it, it is not simply `((body))` (this is here to ensure consistency between content and dev re. our approach to using Notify). 
- [ ] The IDs of all new templates created as part of this issue are documented in this issue. 
- [ ] The placeholders used for each template are documented in this issue along with an explanation of what they are used for. 
- [ ] (Optional) Tickets for changes to **existing** templates have been raised. 

## References

[The official Notify documentation](https://www.notifications.service.gov.uk/using-notify/guidance/edit-and-format-messages).  In particular, please note the section titled 'Personalise your content'

**Comment by bencmitchell** [comment]
Jira: https://dfedigital.atlassian.net/browse/TEVA-1011
