### ISSUE TITLE
A vacancy that has been added cannot be viewed

### ISSUE THREAD

**Issue by milimaldedfe** [DFE-Digital/teacher-vacancy-service#1741]
Bug reported from Zendesk ticket 17075 where a vacancy that has been published and is confirmed as live, but cannot be viewed when searching the site for the role. The role is a Headteacher role at Henry Tyndale School but does not appear when you search for either school name directly or ‘headteacher’. There might be something wrong with the vacancy as the link to their website does not seem to work either. 

Investigate whether this vacancy has definitely been published and why it is not appearing on the site in search results.

Number of users affected: Presumably low (only one instance reported) Severity of inconvenience to users: HighImpact on delivery: M (unknown) 

[https://dfedigital.atlassian.net/browse/TEVA-1013](url)

**Comment by tatyree** [comment]
This is not in the Algolia index yet. That suggests that something in the metadata that controls published status is not as the author expects **or** something has failed in our system.  Investigating.

**Comment by tatyree** [comment]
It should have been indexed on 2020-07-02 and expires on 2020-07-10 11:00:00.  All the metadata was correct.  I have manually indexed it and am looking in to why it did not auto index as expected.

**Comment by tatyree** [comment]
It is unclear why this happened. I'm going to keep an eye on the timed queue and will investigate further if it happens again.

**Comment by cpjmcquillan** [comment]
Neither of the scheduled tasks to index unindexed jobs and delete expired jobs were running due to missing sidekiq configuration
